# Use postgres/example user/password credentials
version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: POSTGRES_DB
    restart: always
    environment:
      POSTGRES_USER: p
      POSTGRES_PASSWORD: p
      POSTGRES_DB: asd
      #POSTGRES_MAX_CONNECTIONS: 10
      #POSTGRES_SHARED_BUFFERS: 256MB
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

  app:
    build: ./
    container_name: golang_container
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: g
      DB_PASSWORD: g
      DB_NAME: asd

volumes:
  postgres-data:
